### ISSUE TITLE
configurable for user

### ISSUE THREAD

**Issue by mies** [wercker/step-add-ssh-key#5]
also root if on docker container:

chown: invalid user: '/tmp/tmp.m1e7Fs4bCP'
chown: invalid user: '/tmp/tmp.m1e7Fs4bCP'
/root/.ssh/config created
/root/.ssh/config updated

**Comment by Mil0dV** [comment]
It seems this is also needed for using the new stack (Ewok). So: +1

**Comment by Mil0dV** [comment]
This is the resulting .ssh/config when using the new stack:

➜  /tmp  cat ./root/.ssh/config
Host *
    IdentityFile /tmp/tmp.CxWwOIsarf
Host *
    IdentityFile

I can see why this doesn't work :). Not sure why this happens/how to prevent this yet, if I figure it out I'll create a PR.

**Comment by flenter** [comment]
I think this is the biggest issue: https://github.com/wercker/step-add-ssh-key/blob/master/run.sh#L26

We need to either remove this line or check if /root (or root user) exists.
Something like: `id -u root` may be used to check if a user exists (returns non 0 exit code if user root doesn't exist). I am not sure how widespread the support for this is

**Comment by Mil0dV** [comment]
There is no root user in Ewok? Then how come /root/.ssh/config is used? 

Some more debugging, the normal /.ssh/config:
Host *
    IdentityFile /tmp/tmp.AEH3pBBeo8

And what I've created as a workaround for now:

    - script:
        name: ssh key fixing
        code: |
          sed -i '3,4d' /root/.ssh/config

**Comment by Mil0dV** [comment]
I think I've figured it out: everything runs as root in Ewok, so #L23 writes incorrect lines to the .ssh/config, after which #L26 prepends them with the correct lines. So the solution seems to be to make #L23 conditional, only run it if the output of 'id -u' > 0. 

Something like this could work:

[[ `id -u` -eq 0 ]] && $WERCKER_STEP_ROOT/addKey.sh $HOME $USER $ssh_key_path $WERCKER_ADD_SSH_KEY_HOST

**Comment by flenter** [comment]
#6 resolved this issue
